version: "3"

volumes:
  postgres_data:

services:
  postgres:
    image: kartoza/postgis:${PG_TAG}
    volumes:
    - postgres_data:/var/lib/postgresql
    ports:
      - "5439:5432"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASS=${PG_PASS}
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4:${PGA_TAG}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

  nginx:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./harjoitukset/build:/www/html
    - ./data:/www/data
    ports:
    - "80:80"
    - "443:443"
