version: "3"

volumes:
  postgres_data:

services:
  db_host:
    image: kartoza/postgis:${PG_TAG}
    volumes:
    - postgres_data:/var/lib/postgresql
    ports:
      - "5439:5432"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASS=${PG_PASS}
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4:${PGA_TAG}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

  client:
    build:
      context: ./docker/client
      args:
        LINUX_USER: ${LINUX_USER}
        LINUX_USER_PASSWORD: ${LINUX_USER_PASSWORD}
    environment:
      - LINUX_USER=${LINUX_USER}
      - POSTGRES_PASS=${PG_PASS}
    depends_on:
      - db_host
    volumes:
    - ./data:/home/${LINUX_USER}/data
    - ./initializer.sh:/initializer.sh

  wetty:
    image: wettyoss/wetty
    depends_on:
      - client
    environment:
      SSHHOST: 'client'
      SSHPORT: 22

  nginx:
    image: nginx
    depends_on:
      - wetty
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./harjoitukset/build:/www/html
    - ./data:/www/data
    ports:
    - "80:80"
    - "443:443"
