name: Render to HTML & Deploy
on:
  repository_dispatch:
    types: [render-deploy]

jobs:
  render-deploy:
    name: Render to HTML & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Render Book
        run: docker-compose up bookdown

      - name: Add, Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          add: "harjoitukset/build"
          message: "Automatic: Update docs"
