name: Update answer tokens
on:
  push:
    paths:
        - 'harjoitukset/build/*.html'

jobs:
  extract-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 14

      - name: Extract Answer Token
        run: |
            for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            if [[ $file == html_files/*.html ]]; then
                title=$(grep -m 1 "<title>.*<\/title>" $file | sed -E 's/<\/?title>//g')
                answerToken=$(node extract-token.js "$title")
                echo "Extracted answer token: $answerToken"
                # Update the README file with the answer token, assuming it's stored in a specific placeholder in the README file
                # sed -i "s/<!-- ANSWER_TOKEN_PLACEHOLDER -->/$answerToken/g" README.md
            fi
            done
